# docker-compose.yml
version: '3.8'

services:

  db:
    image: postgres:15
    container_name: people_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: peopledb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: people_backend
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: people_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000

volumes:
  pgdata: